// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sum_sum,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35ti-csg324-1L,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1068,HLS_SYN_LUT=1824,HLS_VERSION=2022_2}" *)

module sum (
        ap_clk,
        ap_rst_n,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] arr;
wire   [31:0] n;
reg    gmem0_blk_n_AR;
wire    ap_CS_fsm_state2;
reg   [31:0] n_read_reg_134;
reg   [29:0] trunc_ln8_reg_145;
wire   [30:0] empty_17_fu_109_p3;
reg   [30:0] empty_17_reg_151;
wire   [31:0] zext_ln8_fu_127_p1;
wire    grp_sum_Pipeline_sum_loop_fu_80_ap_start;
wire    grp_sum_Pipeline_sum_loop_fu_80_ap_done;
wire    grp_sum_Pipeline_sum_loop_fu_80_ap_idle;
wire    grp_sum_Pipeline_sum_loop_fu_80_ap_ready;
wire    grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWVALID;
wire   [31:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWADDR;
wire   [0:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWID;
wire   [31:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWLEN;
wire   [2:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWSIZE;
wire   [1:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWBURST;
wire   [1:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWLOCK;
wire   [3:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWCACHE;
wire   [2:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWPROT;
wire   [3:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWQOS;
wire   [3:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWREGION;
wire   [0:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWUSER;
wire    grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_WVALID;
wire   [31:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_WDATA;
wire   [3:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_WSTRB;
wire    grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_WLAST;
wire   [0:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_WID;
wire   [0:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_WUSER;
wire    grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARVALID;
wire   [31:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARADDR;
wire   [0:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARID;
wire   [31:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARLEN;
wire   [2:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARSIZE;
wire   [1:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARBURST;
wire   [1:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARLOCK;
wire   [3:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARCACHE;
wire   [2:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARPROT;
wire   [3:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARQOS;
wire   [3:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARREGION;
wire   [0:0] grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARUSER;
wire    grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_RREADY;
wire    grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_BREADY;
wire   [31:0] grp_sum_Pipeline_sum_loop_fu_80_res_out;
wire    grp_sum_Pipeline_sum_loop_fu_80_res_out_ap_vld;
wire    gmem0_AWREADY;
wire    gmem0_WREADY;
reg    gmem0_ARVALID;
wire    gmem0_ARREADY;
reg   [31:0] gmem0_ARADDR;
reg   [31:0] gmem0_ARLEN;
wire    gmem0_RVALID;
reg    gmem0_RREADY;
wire   [31:0] gmem0_RDATA;
wire   [8:0] gmem0_RFIFONUM;
wire    gmem0_BVALID;
reg    grp_sum_Pipeline_sum_loop_fu_80_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire  signed [31:0] sext_ln8_fu_117_p1;
wire    ap_CS_fsm_state11;
wire   [0:0] icmp_ln8_fu_93_p2;
wire   [30:0] empty_fu_89_p1;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ce_reg;
wire   [31:0] ap_return;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 grp_sum_Pipeline_sum_loop_fu_80_ap_start_reg = 1'b0;
end

sum_sum_Pipeline_sum_loop grp_sum_Pipeline_sum_loop_fu_80(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_sum_Pipeline_sum_loop_fu_80_ap_start),
    .ap_done(grp_sum_Pipeline_sum_loop_fu_80_ap_done),
    .ap_idle(grp_sum_Pipeline_sum_loop_fu_80_ap_idle),
    .ap_ready(grp_sum_Pipeline_sum_loop_fu_80_ap_ready),
    .m_axi_gmem0_AWVALID(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(gmem0_RVALID),
    .m_axi_gmem0_RREADY(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(gmem0_RDATA),
    .m_axi_gmem0_RLAST(1'b0),
    .m_axi_gmem0_RID(1'd0),
    .m_axi_gmem0_RFIFONUM(gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(1'd0),
    .m_axi_gmem0_RRESP(2'd0),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .sext_ln8(trunc_ln8_reg_145),
    .n(n_read_reg_134),
    .res_out(grp_sum_Pipeline_sum_loop_fu_80_res_out),
    .res_out_ap_vld(grp_sum_Pipeline_sum_loop_fu_80_res_out_ap_vld)
);

sum_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_return(grp_sum_Pipeline_sum_loop_fu_80_res_out),
    .arr(arr),
    .n(n)
);

sum_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem0_ARVALID),
    .I_ARREADY(gmem0_ARREADY),
    .I_ARADDR(gmem0_ARADDR),
    .I_ARLEN(gmem0_ARLEN),
    .I_RVALID(gmem0_RVALID),
    .I_RREADY(gmem0_RREADY),
    .I_RDATA(gmem0_RDATA),
    .I_RFIFONUM(gmem0_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem0_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem0_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(gmem0_BVALID),
    .I_BREADY(1'b0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_sum_Pipeline_sum_loop_fu_80_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_sum_Pipeline_sum_loop_fu_80_ap_start_reg <= 1'b1;
        end else if ((grp_sum_Pipeline_sum_loop_fu_80_ap_ready == 1'b1)) begin
            grp_sum_Pipeline_sum_loop_fu_80_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_17_reg_151 <= empty_17_fu_109_p3;
        n_read_reg_134 <= n;
        trunc_ln8_reg_145 <= {{arr[31:2]}};
    end
end

always @ (*) begin
    if ((grp_sum_Pipeline_sum_loop_fu_80_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem0_ARADDR = sext_ln8_fu_117_p1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem0_ARADDR = grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARADDR;
    end else begin
        gmem0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem0_ARLEN = zext_ln8_fu_127_p1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem0_ARLEN = grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARLEN;
    end else begin
        gmem0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((gmem0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem0_ARVALID = grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_ARVALID;
    end else begin
        gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem0_RREADY = grp_sum_Pipeline_sum_loop_fu_80_m_axi_gmem0_RREADY;
    end else begin
        gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((gmem0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_sum_Pipeline_sum_loop_fu_80_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_17_fu_109_p3 = ((icmp_ln8_fu_93_p2[0:0] == 1'b1) ? empty_fu_89_p1 : 31'd0);

assign empty_fu_89_p1 = n[30:0];

assign grp_sum_Pipeline_sum_loop_fu_80_ap_start = grp_sum_Pipeline_sum_loop_fu_80_ap_start_reg;

assign icmp_ln8_fu_93_p2 = (($signed(n) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign sext_ln8_fu_117_p1 = $signed(trunc_ln8_reg_145);

assign zext_ln8_fu_127_p1 = empty_17_reg_151;

endmodule //sum
